apiVersion: v1
kind: Pod                   
metadata:           
  name: nginx
  labels:
    app: nginxapp
spec:              
  containers:
  - name: nginx-demo
    image: nginx
    ports:               
    - containerPort: 80
